name: 'Setup'
description: 'Setup environment'
runs:
  using: "composite"
  steps:
    - name: Set Git Config
    - run: |
        git config user.name "php-docblocker"
        git config user.email php-docblocker@brayfield.co.uk

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Cache vscode binary
      uses: actions/cache@v2
      env:
        cache-name: vscode
      with:
        path: ~/.vscode-test/
        key: ${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: npm install
