name: Release
on:
  workflow_dispatch:
    inputs:
        version:
          description: 'Version'
          required: true
          default: 'patch'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install

    - name: Update version number
      run: npm version ${INPUT_VERSION}

    - name: Push
      run: git push
