name: Release
on: workflow_dispatch
  inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install
