name: Release

on:
  pull_request:
    types: [ closed ]

jobs:
  merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

    - name: Output
      run: |
      echo PR #${{ github.event.number }} has been merged
      echo ${{ toJson(github.event) }}
