name: Release

on:
  pull_request:
    types: [ closed ]

jobs:
  merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

    - name: Debug
      uses: hmarr/debug-action@v2

    - name: Output
      run: |
      echo PR #${{ github.event.number }} has been merged
      # echo Logged in as ${{ github.event.pull_request.user.login }}
