name: Test Suite
on: [push, pull_request]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: ./.github/actions/setup

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: xvfb-run -a npm test

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
